// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.scopes {
    exports com.mastfrog.giulius.scope;

    // derived from com.google.inject/guice-0.0.0-? in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires transitive com.google.guice;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan

    // Sibling com.mastfrog/util-strings-3.0.0-dev
    requires com.mastfrog.strings;

    // Inferred from source scan

    // Sibling com.mastfrog/util-function-3.0.0-dev
    requires com.mastfrog.util.function;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive junit;

}
