open module com.mastfrog.scopes {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.scope;

    // derived from com.google.inject/guice-5.1.0 in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires transitive com.google.inject.guice;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.function;
    requires transitive com.mastfrog.util.strings;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
